### ISSUE TITLE
Spotify invalid redirect URI

### ISSUE THREAD

**Issue by Wizz4rrd** [ThePyrotechnic/fortnite_spotify#1]
I've followed all your steps as described, have an registrated application on Spotify and have installed the  script proprely. 

I have, as asked, entered my Spotify Application Client ID and Client Secret. 

Then, I launch the .bat file, says me the following: 

> Activating venv...
> Activated venv.
> A browser window will be opened so that you can authorize this app
> After you press enter, authenticate with Spotify and paste the "code" parameter at the next prompt
> <press Enter to continue>
> Please paste the "code" parameter from the URL here:

A tab opens in Google Chrome saying only the following: 

> INVALID_CLIENT: Invalid redirect URI

I have inserted the URL of the page into my Spotify Application Dashboard under the section Redirect URIs. Deleted of the script, installed it again, and tried. But nothing changed. Still that message of invalid redirect URI

[fortnite_spotify.log](https://github.com/ThePyrotechnic/fortnite_spotify/files/1979924/fortnite_spotify.log)

*****

**EDITs**

- added the log file

**Comment by ThePyrotechnic** [comment]
I forgot to include that step in the installation! It's now step 2: "After registering, go to the [dashboard](https://beta.developer.spotify.com/dashboard/) for that app and click `EDIT SETTINGS`."

Now if you follow the same steps it should work.
