### ISSUE TITLE
Spotify redirect URI

### ISSUE THREAD

**Issue by Wizz4rrd** [ThePyrotechnic/fortnite_spotify#2]
Issue with Spotify's redirect URI. 

Once the Spotify's Application's Client ID and Client Secret it should open a browser tab. A tab opens, I enter my Spotify login and password. But then, the page charge and got following error: 

> This site can’t be reached
> localhost refused to connect.
> Try:
> 
> Checking the connection
> Checking the proxy and the firewall
> ERR_CONNECTION_REFUSED

Checked my Windows Firewall settings, Google Chrome is allowed. Also tried turning my Firewall and anti-virus completely off, and no changes. I also checked my Google Chrome settings (flash, pop-ups, etc) and allowed everything for _localhost_ but still nothing. 

I also tested it with Microsoft Edge and Microsoft Explorer.

Note that between every test I completely deleted all the files and began the installation from zero, just to be sure. 

[fortnite_spotify.log](https://github.com/ThePyrotechnic/fortnite_spotify/files/1981964/fortnite_spotify.log)

**Comment by ThePyrotechnic** [comment]
Ah, yes. I probably should have been more explicit about that. That's supposed to happen actually. If you look in the URL bar after getting that error you'll see a long code. That's actually the key you need to paste into the prompt! I'll link a video of the process and add it to the readme later to help others when this gets polished up.
